/* tslint:disable */
/* eslint-disable */
/**
 * BookMeAPI | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ProblemDetails,
  Result,
  SendCodeRequest,
  VerifyCodeRequest,
} from '../models/index';
import {
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    ResultFromJSON,
    ResultToJSON,
    SendCodeRequestFromJSON,
    SendCodeRequestToJSON,
    VerifyCodeRequestFromJSON,
    VerifyCodeRequestToJSON,
} from '../models/index';

export interface ApiPhoneVerificationSendCodePostRequest {
    sendCodeRequest: SendCodeRequest;
}

export interface ApiPhoneVerificationVerifyCodePostRequest {
    verifyCodeRequest: VerifyCodeRequest;
}

/**
 * 
 */
export class PhoneVerificationApi extends runtime.BaseAPI {

    /**
     */
    async apiPhoneVerificationSendCodePostRaw(requestParameters: ApiPhoneVerificationSendCodePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Result>> {
        if (requestParameters['sendCodeRequest'] == null) {
            throw new runtime.RequiredError(
                'sendCodeRequest',
                'Required parameter "sendCodeRequest" was null or undefined when calling apiPhoneVerificationSendCodePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        const response = await this.request({
            path: `/api/PhoneVerification/send-code`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SendCodeRequestToJSON(requestParameters['sendCodeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultFromJSON(jsonValue));
    }

    /**
     */
    async apiPhoneVerificationSendCodePost(requestParameters: ApiPhoneVerificationSendCodePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Result> {
        const response = await this.apiPhoneVerificationSendCodePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPhoneVerificationVerifyCodePostRaw(requestParameters: ApiPhoneVerificationVerifyCodePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Result>> {
        if (requestParameters['verifyCodeRequest'] == null) {
            throw new runtime.RequiredError(
                'verifyCodeRequest',
                'Required parameter "verifyCodeRequest" was null or undefined when calling apiPhoneVerificationVerifyCodePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        const response = await this.request({
            path: `/api/PhoneVerification/verify-code`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifyCodeRequestToJSON(requestParameters['verifyCodeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultFromJSON(jsonValue));
    }

    /**
     */
    async apiPhoneVerificationVerifyCodePost(requestParameters: ApiPhoneVerificationVerifyCodePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Result> {
        const response = await this.apiPhoneVerificationVerifyCodePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
