/* tslint:disable */
/* eslint-disable */
/**
 * BookMeAPI | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookTimeSlotsDto
 */
export interface BookTimeSlotsDto {
    /**
     * 
     * @type {string}
     * @memberof BookTimeSlotsDto
     */
    timeSlotId?: string;
}

/**
 * Check if a given object implements the BookTimeSlotsDto interface.
 */
export function instanceOfBookTimeSlotsDto(value: object): value is BookTimeSlotsDto {
    return true;
}

export function BookTimeSlotsDtoFromJSON(json: any): BookTimeSlotsDto {
    return BookTimeSlotsDtoFromJSONTyped(json, false);
}

export function BookTimeSlotsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookTimeSlotsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'timeSlotId': json['timeSlotId'] == null ? undefined : json['timeSlotId'],
    };
}

export function BookTimeSlotsDtoToJSON(json: any): BookTimeSlotsDto {
    return BookTimeSlotsDtoToJSONTyped(json, false);
}

export function BookTimeSlotsDtoToJSONTyped(value?: BookTimeSlotsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timeSlotId': value['timeSlotId'],
    };
}

