/* tslint:disable */
/* eslint-disable */
/**
 * BookMeAPI | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeSlotDto2 } from './TimeSlotDto2';
import {
    TimeSlotDto2FromJSON,
    TimeSlotDto2FromJSONTyped,
    TimeSlotDto2ToJSON,
    TimeSlotDto2ToJSONTyped,
} from './TimeSlotDto2';
import type { UserDto2 } from './UserDto2';
import {
    UserDto2FromJSON,
    UserDto2FromJSONTyped,
    UserDto2ToJSON,
    UserDto2ToJSONTyped,
} from './UserDto2';

/**
 * 
 * @export
 * @interface BookingDto
 */
export interface BookingDto {
    /**
     * 
     * @type {string}
     * @memberof BookingDto
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof BookingDto
     */
    status?: number;
    /**
     * 
     * @type {UserDto2}
     * @memberof BookingDto
     */
    user?: UserDto2 | null;
    /**
     * 
     * @type {TimeSlotDto2}
     * @memberof BookingDto
     */
    timeSlot?: TimeSlotDto2 | null;
}

/**
 * Check if a given object implements the BookingDto interface.
 */
export function instanceOfBookingDto(value: object): value is BookingDto {
    return true;
}

export function BookingDtoFromJSON(json: any): BookingDto {
    return BookingDtoFromJSONTyped(json, false);
}

export function BookingDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'status': json['status'] == null ? undefined : json['status'],
        'user': json['user'] == null ? undefined : UserDto2FromJSON(json['user']),
        'timeSlot': json['timeSlot'] == null ? undefined : TimeSlotDto2FromJSON(json['timeSlot']),
    };
}

export function BookingDtoToJSON(json: any): BookingDto {
    return BookingDtoToJSONTyped(json, false);
}

export function BookingDtoToJSONTyped(value?: BookingDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
        'user': UserDto2ToJSON(value['user']),
        'timeSlot': TimeSlotDto2ToJSON(value['timeSlot']),
    };
}

