/* tslint:disable */
/* eslint-disable */
/**
 * BookMeAPI | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CancelBookingDto
 */
export interface CancelBookingDto {
    /**
     * 
     * @type {string}
     * @memberof CancelBookingDto
     */
    bookingId?: string;
}

/**
 * Check if a given object implements the CancelBookingDto interface.
 */
export function instanceOfCancelBookingDto(value: object): value is CancelBookingDto {
    return true;
}

export function CancelBookingDtoFromJSON(json: any): CancelBookingDto {
    return CancelBookingDtoFromJSONTyped(json, false);
}

export function CancelBookingDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CancelBookingDto {
    if (json == null) {
        return json;
    }
    return {
        
        'bookingId': json['bookingId'] == null ? undefined : json['bookingId'],
    };
}

export function CancelBookingDtoToJSON(json: any): CancelBookingDto {
    return CancelBookingDtoToJSONTyped(json, false);
}

export function CancelBookingDtoToJSONTyped(value?: CancelBookingDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bookingId': value['bookingId'],
    };
}

