/* tslint:disable */
/* eslint-disable */
/**
 * BookMeAPI | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfirmBookingDto
 */
export interface ConfirmBookingDto {
    /**
     * 
     * @type {string}
     * @memberof ConfirmBookingDto
     */
    bookingId?: string;
}

/**
 * Check if a given object implements the ConfirmBookingDto interface.
 */
export function instanceOfConfirmBookingDto(value: object): value is ConfirmBookingDto {
    return true;
}

export function ConfirmBookingDtoFromJSON(json: any): ConfirmBookingDto {
    return ConfirmBookingDtoFromJSONTyped(json, false);
}

export function ConfirmBookingDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmBookingDto {
    if (json == null) {
        return json;
    }
    return {
        
        'bookingId': json['bookingId'] == null ? undefined : json['bookingId'],
    };
}

export function ConfirmBookingDtoToJSON(json: any): ConfirmBookingDto {
    return ConfirmBookingDtoToJSONTyped(json, false);
}

export function ConfirmBookingDtoToJSONTyped(value?: ConfirmBookingDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bookingId': value['bookingId'],
    };
}

