/* tslint:disable */
/* eslint-disable */
/**
 * BookMeAPI | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAvailableTimeSlotsDto
 */
export interface GetAvailableTimeSlotsDto {
    /**
     * 
     * @type {Date}
     * @memberof GetAvailableTimeSlotsDto
     */
    start?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetAvailableTimeSlotsDto
     */
    end?: Date;
}

/**
 * Check if a given object implements the GetAvailableTimeSlotsDto interface.
 */
export function instanceOfGetAvailableTimeSlotsDto(value: object): value is GetAvailableTimeSlotsDto {
    return true;
}

export function GetAvailableTimeSlotsDtoFromJSON(json: any): GetAvailableTimeSlotsDto {
    return GetAvailableTimeSlotsDtoFromJSONTyped(json, false);
}

export function GetAvailableTimeSlotsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAvailableTimeSlotsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'start': json['start'] == null ? undefined : (new Date(json['start'])),
        'end': json['end'] == null ? undefined : (new Date(json['end'])),
    };
}

export function GetAvailableTimeSlotsDtoToJSON(json: any): GetAvailableTimeSlotsDto {
    return GetAvailableTimeSlotsDtoToJSONTyped(json, false);
}

export function GetAvailableTimeSlotsDtoToJSONTyped(value?: GetAvailableTimeSlotsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start': value['start'] == null ? undefined : ((value['start']).toISOString()),
        'end': value['end'] == null ? undefined : ((value['end']).toISOString()),
    };
}

