/* tslint:disable */
/* eslint-disable */
/**
 * BookMeAPI | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAvailableDatesResponseDto
 */
export interface GetAvailableDatesResponseDto {
    /**
     * 
     * @type {Array<Date>}
     * @memberof GetAvailableDatesResponseDto
     */
    dates?: Array<Date> | null;
}

/**
 * Check if a given object implements the GetAvailableDatesResponseDto interface.
 */
export function instanceOfGetAvailableDatesResponseDto(value: object): value is GetAvailableDatesResponseDto {
    return true;
}

export function GetAvailableDatesResponseDtoFromJSON(json: any): GetAvailableDatesResponseDto {
    return GetAvailableDatesResponseDtoFromJSONTyped(json, false);
}

export function GetAvailableDatesResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAvailableDatesResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'dates': json['dates'] == null ? undefined : json['dates'],
    };
}

export function GetAvailableDatesResponseDtoToJSON(json: any): GetAvailableDatesResponseDto {
    return GetAvailableDatesResponseDtoToJSONTyped(json, false);
}

export function GetAvailableDatesResponseDtoToJSONTyped(value?: GetAvailableDatesResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dates': value['dates'],
    };
}

