/* tslint:disable */
/* eslint-disable */
/**
 * BookMeAPI | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAvailableDatesDto
 */
export interface GetAvailableDatesDto {
    /**
     * 
     * @type {Date}
     * @memberof GetAvailableDatesDto
     */
    start?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetAvailableDatesDto
     */
    end?: Date;
}

/**
 * Check if a given object implements the GetAvailableDatesDto interface.
 */
export function instanceOfGetAvailableDatesDto(value: object): value is GetAvailableDatesDto {
    return true;
}

export function GetAvailableDatesDtoFromJSON(json: any): GetAvailableDatesDto {
    return GetAvailableDatesDtoFromJSONTyped(json, false);
}

export function GetAvailableDatesDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAvailableDatesDto {
    if (json == null) {
        return json;
    }
    return {
        
        'start': json['start'] == null ? undefined : (new Date(json['start'])),
        'end': json['end'] == null ? undefined : (new Date(json['end'])),
    };
}

export function GetAvailableDatesDtoToJSON(json: any): GetAvailableDatesDto {
    return GetAvailableDatesDtoToJSONTyped(json, false);
}

export function GetAvailableDatesDtoToJSONTyped(value?: GetAvailableDatesDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start': value['start'] == null ? undefined : ((value['start']).toISOString()),
        'end': value['end'] == null ? undefined : ((value['end']).toISOString()),
    };
}

