/* tslint:disable */
/* eslint-disable */
/**
 * BookMeAPI | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetTimeSlotsDto
 */
export interface GetTimeSlotsDto {
    /**
     * 
     * @type {Date}
     * @memberof GetTimeSlotsDto
     */
    start?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetTimeSlotsDto
     */
    end?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof GetTimeSlotsDto
     */
    isAvailable?: boolean;
}

/**
 * Check if a given object implements the GetTimeSlotsDto interface.
 */
export function instanceOfGetTimeSlotsDto(value: object): value is GetTimeSlotsDto {
    return true;
}

export function GetTimeSlotsDtoFromJSON(json: any): GetTimeSlotsDto {
    return GetTimeSlotsDtoFromJSONTyped(json, false);
}

export function GetTimeSlotsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTimeSlotsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'start': json['start'] == null ? undefined : (new Date(json['start'])),
        'end': json['end'] == null ? undefined : (new Date(json['end'])),
        'isAvailable': json['isAvailable'] == null ? undefined : json['isAvailable'],
    };
}

export function GetTimeSlotsDtoToJSON(json: any): GetTimeSlotsDto {
    return GetTimeSlotsDtoToJSONTyped(json, false);
}

export function GetTimeSlotsDtoToJSONTyped(value?: GetTimeSlotsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start': value['start'] == null ? undefined : ((value['start']).toISOString()),
        'end': value['end'] == null ? undefined : ((value['end']).toISOString()),
        'isAvailable': value['isAvailable'],
    };
}

