/* tslint:disable */
/* eslint-disable */
/**
 * BookMeAPI | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserDto } from './UserDto';
import {
    UserDtoFromJSON,
    UserDtoFromJSONTyped,
    UserDtoToJSON,
    UserDtoToJSONTyped,
} from './UserDto';

/**
 * 
 * @export
 * @interface PagedListDtoOfUserDto
 */
export interface PagedListDtoOfUserDto {
    /**
     * 
     * @type {number}
     * @memberof PagedListDtoOfUserDto
     */
    pageIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof PagedListDtoOfUserDto
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof PagedListDtoOfUserDto
     */
    totalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof PagedListDtoOfUserDto
     */
    totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PagedListDtoOfUserDto
     */
    hasPreviousPage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PagedListDtoOfUserDto
     */
    hasNextPage?: boolean;
    /**
     * 
     * @type {Array<UserDto>}
     * @memberof PagedListDtoOfUserDto
     */
    items?: Array<UserDto> | null;
}

/**
 * Check if a given object implements the PagedListDtoOfUserDto interface.
 */
export function instanceOfPagedListDtoOfUserDto(value: object): value is PagedListDtoOfUserDto {
    return true;
}

export function PagedListDtoOfUserDtoFromJSON(json: any): PagedListDtoOfUserDto {
    return PagedListDtoOfUserDtoFromJSONTyped(json, false);
}

export function PagedListDtoOfUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedListDtoOfUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'pageIndex': json['pageIndex'] == null ? undefined : json['pageIndex'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'hasPreviousPage': json['hasPreviousPage'] == null ? undefined : json['hasPreviousPage'],
        'hasNextPage': json['hasNextPage'] == null ? undefined : json['hasNextPage'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(UserDtoFromJSON)),
    };
}

export function PagedListDtoOfUserDtoToJSON(json: any): PagedListDtoOfUserDto {
    return PagedListDtoOfUserDtoToJSONTyped(json, false);
}

export function PagedListDtoOfUserDtoToJSONTyped(value?: PagedListDtoOfUserDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pageIndex': value['pageIndex'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'totalPages': value['totalPages'],
        'hasPreviousPage': value['hasPreviousPage'],
        'hasNextPage': value['hasNextPage'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(UserDtoToJSON)),
    };
}

