/* tslint:disable */
/* eslint-disable */
/**
 * BookMeAPI | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeSlotDto } from './TimeSlotDto';
import {
    TimeSlotDtoFromJSON,
    TimeSlotDtoFromJSONTyped,
    TimeSlotDtoToJSON,
    TimeSlotDtoToJSONTyped,
} from './TimeSlotDto';

/**
 * 
 * @export
 * @interface PagedListDtoOfTimeSlotDto
 */
export interface PagedListDtoOfTimeSlotDto {
    /**
     * 
     * @type {number}
     * @memberof PagedListDtoOfTimeSlotDto
     */
    pageIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof PagedListDtoOfTimeSlotDto
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof PagedListDtoOfTimeSlotDto
     */
    totalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof PagedListDtoOfTimeSlotDto
     */
    totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PagedListDtoOfTimeSlotDto
     */
    hasPreviousPage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PagedListDtoOfTimeSlotDto
     */
    hasNextPage?: boolean;
    /**
     * 
     * @type {Array<TimeSlotDto>}
     * @memberof PagedListDtoOfTimeSlotDto
     */
    items?: Array<TimeSlotDto> | null;
}

/**
 * Check if a given object implements the PagedListDtoOfTimeSlotDto interface.
 */
export function instanceOfPagedListDtoOfTimeSlotDto(value: object): value is PagedListDtoOfTimeSlotDto {
    return true;
}

export function PagedListDtoOfTimeSlotDtoFromJSON(json: any): PagedListDtoOfTimeSlotDto {
    return PagedListDtoOfTimeSlotDtoFromJSONTyped(json, false);
}

export function PagedListDtoOfTimeSlotDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedListDtoOfTimeSlotDto {
    if (json == null) {
        return json;
    }
    return {
        
        'pageIndex': json['pageIndex'] == null ? undefined : json['pageIndex'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'hasPreviousPage': json['hasPreviousPage'] == null ? undefined : json['hasPreviousPage'],
        'hasNextPage': json['hasNextPage'] == null ? undefined : json['hasNextPage'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(TimeSlotDtoFromJSON)),
    };
}

export function PagedListDtoOfTimeSlotDtoToJSON(json: any): PagedListDtoOfTimeSlotDto {
    return PagedListDtoOfTimeSlotDtoToJSONTyped(json, false);
}

export function PagedListDtoOfTimeSlotDtoToJSONTyped(value?: PagedListDtoOfTimeSlotDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pageIndex': value['pageIndex'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'totalPages': value['totalPages'],
        'hasPreviousPage': value['hasPreviousPage'],
        'hasNextPage': value['hasNextPage'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(TimeSlotDtoToJSON)),
    };
}

