/* tslint:disable */
/* eslint-disable */
/**
 * BookMeAPI | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookingDto2 } from './BookingDto2';
import {
    BookingDto2FromJSON,
    BookingDto2FromJSONTyped,
    BookingDto2ToJSON,
    BookingDto2ToJSONTyped,
} from './BookingDto2';

/**
 * 
 * @export
 * @interface ResultOfBookingDto
 */
export interface ResultOfBookingDto {
    /**
     * 
     * @type {BookingDto2}
     * @memberof ResultOfBookingDto
     */
    value?: BookingDto2 | null;
    /**
     * 
     * @type {boolean}
     * @memberof ResultOfBookingDto
     */
    isSuccess?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ResultOfBookingDto
     */
    isFailure?: boolean;
    /**
     * 
     * @type {Array<Error>}
     * @memberof ResultOfBookingDto
     */
    errors?: Array<Error> | null;
    /**
     * 
     * @type {number}
     * @memberof ResultOfBookingDto
     */
    successType?: number;
}

/**
 * Check if a given object implements the ResultOfBookingDto interface.
 */
export function instanceOfResultOfBookingDto(value: object): value is ResultOfBookingDto {
    return true;
}

export function ResultOfBookingDtoFromJSON(json: any): ResultOfBookingDto {
    return ResultOfBookingDtoFromJSONTyped(json, false);
}

export function ResultOfBookingDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultOfBookingDto {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : BookingDto2FromJSON(json['value']),
        'isSuccess': json['isSuccess'] == null ? undefined : json['isSuccess'],
        'isFailure': json['isFailure'] == null ? undefined : json['isFailure'],
        'errors': json['errors'] == null ? undefined : json['errors'],
        'successType': json['successType'] == null ? undefined : json['successType'],
    };
}

export function ResultOfBookingDtoToJSON(json: any): ResultOfBookingDto {
    return ResultOfBookingDtoToJSONTyped(json, false);
}

export function ResultOfBookingDtoToJSONTyped(value?: ResultOfBookingDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': BookingDto2ToJSON(value['value']),
        'isSuccess': value['isSuccess'],
        'isFailure': value['isFailure'],
        'errors': value['errors'],
        'successType': value['successType'],
    };
}

