/* tslint:disable */
/* eslint-disable */
/**
 * BookMeAPI | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendCodeRequest
 */
export interface SendCodeRequest {
    /**
     * 
     * @type {string}
     * @memberof SendCodeRequest
     */
    phoneNumber?: string | null;
}

/**
 * Check if a given object implements the SendCodeRequest interface.
 */
export function instanceOfSendCodeRequest(value: object): value is SendCodeRequest {
    return true;
}

export function SendCodeRequestFromJSON(json: any): SendCodeRequest {
    return SendCodeRequestFromJSONTyped(json, false);
}

export function SendCodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendCodeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
    };
}

export function SendCodeRequestToJSON(json: any): SendCodeRequest {
    return SendCodeRequestToJSONTyped(json, false);
}

export function SendCodeRequestToJSONTyped(value?: SendCodeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'phoneNumber': value['phoneNumber'],
    };
}

