/* tslint:disable */
/* eslint-disable */
/**
 * BookMeAPI | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimeSlotDto
 */
export interface TimeSlotDto {
    /**
     * 
     * @type {string}
     * @memberof TimeSlotDto
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof TimeSlotDto
     */
    start?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TimeSlotDto
     */
    end?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof TimeSlotDto
     */
    isAvailable?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TimeSlotDto
     */
    allowAutoConfirmation?: boolean | null;
}

/**
 * Check if a given object implements the TimeSlotDto interface.
 */
export function instanceOfTimeSlotDto(value: object): value is TimeSlotDto {
    return true;
}

export function TimeSlotDtoFromJSON(json: any): TimeSlotDto {
    return TimeSlotDtoFromJSONTyped(json, false);
}

export function TimeSlotDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeSlotDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'start': json['start'] == null ? undefined : (new Date(json['start'])),
        'end': json['end'] == null ? undefined : (new Date(json['end'])),
        'isAvailable': json['isAvailable'] == null ? undefined : json['isAvailable'],
        'allowAutoConfirmation': json['allowAutoConfirmation'] == null ? undefined : json['allowAutoConfirmation'],
    };
}

export function TimeSlotDtoToJSON(json: any): TimeSlotDto {
    return TimeSlotDtoToJSONTyped(json, false);
}

export function TimeSlotDtoToJSONTyped(value?: TimeSlotDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'start': value['start'] == null ? undefined : ((value['start']).toISOString()),
        'end': value['end'] == null ? undefined : ((value['end']).toISOString()),
        'isAvailable': value['isAvailable'],
        'allowAutoConfirmation': value['allowAutoConfirmation'],
    };
}

