/* tslint:disable */
/* eslint-disable */
/**
 * BookMeAPI | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimeSlotDto2
 */
export interface TimeSlotDto2 {
    /**
     * 
     * @type {string}
     * @memberof TimeSlotDto2
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof TimeSlotDto2
     */
    start?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TimeSlotDto2
     */
    end?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof TimeSlotDto2
     */
    isAvailable?: boolean;
}

/**
 * Check if a given object implements the TimeSlotDto2 interface.
 */
export function instanceOfTimeSlotDto2(value: object): value is TimeSlotDto2 {
    return true;
}

export function TimeSlotDto2FromJSON(json: any): TimeSlotDto2 {
    return TimeSlotDto2FromJSONTyped(json, false);
}

export function TimeSlotDto2FromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeSlotDto2 {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'start': json['start'] == null ? undefined : (new Date(json['start'])),
        'end': json['end'] == null ? undefined : (new Date(json['end'])),
        'isAvailable': json['isAvailable'] == null ? undefined : json['isAvailable'],
    };
}

export function TimeSlotDto2ToJSON(json: any): TimeSlotDto2 {
    return TimeSlotDto2ToJSONTyped(json, false);
}

export function TimeSlotDto2ToJSONTyped(value?: TimeSlotDto2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'start': value['start'] == null ? undefined : ((value['start']).toISOString()),
        'end': value['end'] == null ? undefined : ((value['end']).toISOString()),
        'isAvailable': value['isAvailable'],
    };
}

