/* tslint:disable */
/* eslint-disable */
/**
 * BookMeAPI | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRoleDto2 } from './UserRoleDto2';
import {
    UserRoleDto2FromJSON,
    UserRoleDto2FromJSONTyped,
    UserRoleDto2ToJSON,
    UserRoleDto2ToJSONTyped,
} from './UserRoleDto2';

/**
 * 
 * @export
 * @interface UserDto3
 */
export interface UserDto3 {
    /**
     * 
     * @type {string}
     * @memberof UserDto3
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto3
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDto3
     */
    surname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDto3
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDto3
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {Array<UserRoleDto2>}
     * @memberof UserDto3
     */
    roles?: Array<UserRoleDto2> | null;
}

/**
 * Check if a given object implements the UserDto3 interface.
 */
export function instanceOfUserDto3(value: object): value is UserDto3 {
    return true;
}

export function UserDto3FromJSON(json: any): UserDto3 {
    return UserDto3FromJSONTyped(json, false);
}

export function UserDto3FromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDto3 {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'surname': json['surname'] == null ? undefined : json['surname'],
        'email': json['email'] == null ? undefined : json['email'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'roles': json['roles'] == null ? undefined : ((json['roles'] as Array<any>).map(UserRoleDto2FromJSON)),
    };
}

export function UserDto3ToJSON(json: any): UserDto3 {
    return UserDto3ToJSONTyped(json, false);
}

export function UserDto3ToJSONTyped(value?: UserDto3 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'surname': value['surname'],
        'email': value['email'],
        'phoneNumber': value['phoneNumber'],
        'roles': value['roles'] == null ? undefined : ((value['roles'] as Array<any>).map(UserRoleDto2ToJSON)),
    };
}

