/* tslint:disable */
/* eslint-disable */
/**
 * BookMeAPI | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Roles } from './Roles';
import {
    RolesFromJSON,
    RolesFromJSONTyped,
    RolesToJSON,
    RolesToJSONTyped,
} from './Roles';

/**
 * 
 * @export
 * @interface UserDto4
 */
export interface UserDto4 {
    /**
     * 
     * @type {string}
     * @memberof UserDto4
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto4
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDto4
     */
    surname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDto4
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDto4
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {Roles}
     * @memberof UserDto4
     */
    roles?: Roles;
}

/**
 * Check if a given object implements the UserDto4 interface.
 */
export function instanceOfUserDto4(value: object): value is UserDto4 {
    return true;
}

export function UserDto4FromJSON(json: any): UserDto4 {
    return UserDto4FromJSONTyped(json, false);
}

export function UserDto4FromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDto4 {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'surname': json['surname'] == null ? undefined : json['surname'],
        'email': json['email'] == null ? undefined : json['email'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'roles': json['roles'] == null ? undefined : RolesFromJSON(json['roles']),
    };
}

export function UserDto4ToJSON(json: any): UserDto4 {
    return UserDto4ToJSONTyped(json, false);
}

export function UserDto4ToJSONTyped(value?: UserDto4 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'surname': value['surname'],
        'email': value['email'],
        'phoneNumber': value['phoneNumber'],
        'roles': RolesToJSON(value['roles']),
    };
}

