/* tslint:disable */
/* eslint-disable */
/**
 * BookMeAPI | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoleDto } from './RoleDto';
import {
    RoleDtoFromJSON,
    RoleDtoFromJSONTyped,
    RoleDtoToJSON,
    RoleDtoToJSONTyped,
} from './RoleDto';
import type { UserDto4 } from './UserDto4';
import {
    UserDto4FromJSON,
    UserDto4FromJSONTyped,
    UserDto4ToJSON,
    UserDto4ToJSONTyped,
} from './UserDto4';

/**
 * 
 * @export
 * @interface UserRoleDto2
 */
export interface UserRoleDto2 {
    /**
     * 
     * @type {UserDto4}
     * @memberof UserRoleDto2
     */
    user?: UserDto4 | null;
    /**
     * 
     * @type {RoleDto}
     * @memberof UserRoleDto2
     */
    role?: RoleDto | null;
}

/**
 * Check if a given object implements the UserRoleDto2 interface.
 */
export function instanceOfUserRoleDto2(value: object): value is UserRoleDto2 {
    return true;
}

export function UserRoleDto2FromJSON(json: any): UserRoleDto2 {
    return UserRoleDto2FromJSONTyped(json, false);
}

export function UserRoleDto2FromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRoleDto2 {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'] == null ? undefined : UserDto4FromJSON(json['user']),
        'role': json['role'] == null ? undefined : RoleDtoFromJSON(json['role']),
    };
}

export function UserRoleDto2ToJSON(json: any): UserRoleDto2 {
    return UserRoleDto2ToJSONTyped(json, false);
}

export function UserRoleDto2ToJSONTyped(value?: UserRoleDto2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': UserDto4ToJSON(value['user']),
        'role': RoleDtoToJSON(value['role']),
    };
}

