# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    # services:
      # Add SQL Server service container for integration tests
      # mssql:
      #   image: mcr.microsoft.com/mssql/server:2022-latest
      #   env:
      #     SA_PASSWORD: TestDb1234_
      #     ACCEPT_EULA: Y
      #   ports:
      #     - 1433:1433
      #   options: >-
      #     --health-cmd="/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P TestDb1234_ -Q 'SELECT 1' || exit 1"
      #     --health-interval 10s
      #     --health-timeout 5s
      #     --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Unit Tests
      run: dotnet test tests/BookMe.Unitests/BookMe.UnitTests.csproj --no-build --verbosity normal
    - name: Integration Tests
      run: dotnet test tests/BookMe.IntegrationTests/BookMe.IntegrationTests.csproj --no-build --verbosity normal
